//! GRGM1200A spherical harmonic coefficient storage and retrieval.
//!
//! The binary blob is generated by `tools/gen_coefficients.py` and bundled
//! into the WASM binary via `include_bytes!`.
//!
//! Binary format (little-endian):
//!   bytes 0–3:  N_MAX as u32_le
//!   bytes 4+:   for n in 0..=N_MAX, for m in 0..=n:
//!                 C_nm: f64_le (8 bytes)
//!                 S_nm: f64_le (8 bytes)
//!
//! Index formula: pair_index(n, m) = n*(n+1)/2 + m
//! Data index:    data[2 * pair_index(n, m)]     = C_nm
//!                data[2 * pair_index(n, m) + 1] = S_nm

/// Reference radius for GRGM1200A [km].
/// Used in the (R_ref/r)^n ratio for the potential expansion.
pub const R_REF: f64 = 1738.0;

/// Bundled 100×100 GRGM1200A binary blob (compiled into the WASM binary).
static GRGM1200A_BIN: &[u8] = include_bytes!("../data/grgm1200a_100x100.bin");

// ─── Coefficient store ────────────────────────────────────────────────────────

pub struct Coefficients {
    /// Maximum degree/order loaded (capped at the binary file's N_MAX).
    pub n_max: usize,
    /// Flat storage: index 2*(n*(n+1)/2 + m) = C_nm; +1 = S_nm.
    data: Vec<f64>,
}

impl Coefficients {
    /// Load from the bundled GRGM1200A binary, truncated to `n_max_request`.
    pub fn from_bundle(n_max_request: usize) -> Coefficients {
        Self::parse(GRGM1200A_BIN, n_max_request)
    }

    /// Load from an externally-provided byte slice.
    /// Useful for the `load_coefficients` WASM API (user uploads their own file).
    pub fn from_bytes(bytes: &[u8], n_max_request: usize) -> Coefficients {
        Self::parse(bytes, n_max_request)
    }

    fn parse(bytes: &[u8], n_max_request: usize) -> Coefficients {
        if bytes.len() < 4 {
            return Coefficients { n_max: 0, data: vec![1.0, 0.0] };
        }

        let file_n_max = u32::from_le_bytes(bytes[0..4].try_into().unwrap()) as usize;
        let n_max      = n_max_request.min(file_n_max);
        let n_pairs    = (n_max + 1) * (n_max + 2) / 2;
        let mut data   = vec![0.0f64; n_pairs * 2];

        let mut pos = 4usize;
        for n in 0..=file_n_max {
            for m in 0..=n {
                if pos + 16 > bytes.len() { break; }
                let c = f64::from_le_bytes(bytes[pos..pos+8].try_into().unwrap());
                let s = f64::from_le_bytes(bytes[pos+8..pos+16].try_into().unwrap());
                pos += 16;
                if n <= n_max {
                    let idx = 2 * (n * (n + 1) / 2 + m);
                    data[idx]     = c;
                    data[idx + 1] = s;
                }
            }
        }

        Coefficients { n_max, data }
    }

    /// Get (C_nm, S_nm). Returns (0, 0) for out-of-range indices.
    #[inline(always)]
    pub fn get(&self, n: usize, m: usize) -> (f64, f64) {
        if n > self.n_max || m > n {
            return (0.0, 0.0);
        }
        let idx = 2 * (n * (n + 1) / 2 + m);
        (self.data[idx], self.data[idx + 1])
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn c00_is_one() {
        // C_00 = 1 by definition (potential normalisation).
        let c = Coefficients::from_bundle(4);
        let (c00, s00) = c.get(0, 0);
        assert!((c00 - 1.0).abs() < 1e-10, "C00 = {} (expected 1.0)", c00);
        assert!(s00.abs() < 1e-15, "S00 = {} (expected 0)", s00);
    }

    #[test]
    fn j2_value_in_range() {
        // GRGM1200A C_20 (fully normalised) ≈ −9.095×10⁻⁴.
        let c = Coefficients::from_bundle(4);
        let (c20, _) = c.get(2, 0);
        assert!(
            c20 < -8.0e-4 && c20 > -1.0e-3,
            "C20 = {:.6e} out of expected GRGM1200A range (−8e−4, −1e−3)", c20
        );
    }

    #[test]
    fn c22_nonzero() {
        // C_22 drives lunar triaxiality — must be ≈ 3.4×10⁻⁵.
        let c = Coefficients::from_bundle(4);
        let (c22, _) = c.get(2, 2);
        assert!(c22 > 1.0e-6, "C22 = {:.3e} suspiciously small", c22);
    }

    #[test]
    fn n_max_clamp() {
        let c = Coefficients::from_bundle(10);
        assert_eq!(c.n_max, 10);
        // (10, 5) must be accessible without panic
        let _ = c.get(10, 5);
        // Out-of-range returns zero
        let (c_oob, _) = c.get(11, 0);
        assert_eq!(c_oob, 0.0);
    }

    #[test]
    fn index_formula_correct() {
        // Verify the pair_index formula: index(n, m) = n*(n+1)/2 + m
        // n=2, m=0 → index 3; n=2, m=2 → index 5
        let c = Coefficients::from_bundle(2);
        let (c20a, _) = c.get(2, 0);
        let (c20b, _) = c.get(2, 0);
        assert_eq!(c20a, c20b, "Repeated lookup should return same value");
    }
}
